# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 408c7674fc34e993f84ffeedf656d622c4ef83b5fc708c122841603b5194ba5c151e94a0e8e4f38271c7ddc1124868394ea4ca54ac6f3f4db5b2c6c851c2ce20

test:
  secret_key_base: 3073c02a7f5199bdb90542cf35f4f65f0c49a0465c657e7c91f4dc48e81eb5ddbd70c5d430f08cf35b16b45ec196f05a288681fa2494d1c5be9c5251d0b42cfd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
